[project]
name = "soybean-leaf-pest-damage"
version = "0.1.0"
description = "Soybean leaf pest damage classification using CNN"
readme = "README.md"
requires-python = "==3.12.7"
dependencies = [
    "tensorflow[and-cuda]==2.17.1",
    "pandas",
    "numpy",
    "matplotlib",
    "seaborn",
    "scikit-learn",
    "PyYAML",
    "tqdm",
    "ensure==1.0.2",
    "joblib",
    "types-PyYAML",
    "scipy",
    "Flask",
    "Flask-Cors",
    "gdown",
    "loguru",
    "setuptools",
]

[dependency-groups]
dev = [
    "dvc>=3.60.1",
    "notebook>=7.4.3",
]

[tool.uv.sources]
soybean-leaf-pest-damage = { workspace = true }

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"